/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InterfaceGrafica.java
 *
 * Created on 27/09/2010, 18:36:35
 */
package roundrobin;

import java.awt.Component;
import javax.swing.SpinnerNumberModel;
import javax.swing.UIManager;

/**
 *
 * @author Diogo
 */
public class InterfaceGrafica extends javax.swing.JFrame {

    /** Creates new form InterfaceGrafica */
    public InterfaceGrafica() {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
        } catch (Exception e) {
            e.printStackTrace();
        }
        initComponents();
        setLocationRelativeTo(null); //centralizar
        jPanel_processo5.setVisible(false);
        jSpinner_quantum.setModel(new SpinnerNumberModel(10, 1, 1000, 1));
        jSpinner_overhead.setModel(new SpinnerNumberModel(1, 0, 100, 1));
        setSpinnerModels();
    }

    void setSpinnerModels() {
        jSpinner_chegadaProcesso1.setModel(new SpinnerNumberModel(0, 0, 1000, 1));
        jSpinner_chegadaProcesso2.setModel(new SpinnerNumberModel(0, 0, 1000, 1));
        jSpinner_chegadaProcesso3.setModel(new SpinnerNumberModel(0, 0, 1000, 1));
        jSpinner_chegadaProcesso4.setModel(new SpinnerNumberModel(0, 0, 1000, 1));
        jSpinner_chegadaProcesso5.setModel(new SpinnerNumberModel(0, 0, 1000, 1));
        jSpinner_duracaoProcesso1.setModel(new SpinnerNumberModel(10, 1, 1000, 1));
        jSpinner_duracaoProcesso2.setModel(new SpinnerNumberModel(10, 1, 1000, 1));
        jSpinner_duracaoProcesso3.setModel(new SpinnerNumberModel(10, 1, 1000, 1));
        jSpinner_duracaoProcesso4.setModel(new SpinnerNumberModel(10, 1, 1000, 1));
        jSpinner_duracaoProcesso5.setModel(new SpinnerNumberModel(10, 1, 1000, 1));
        jSpinner_bloqueioProcesso1.setModel(new SpinnerNumberModel(5, 1, ((SpinnerNumberModel) (jSpinner_duracaoProcesso1.getModel())).getNumber().intValue(), 1));
        jSpinner_bloqueioProcesso2.setModel(new SpinnerNumberModel(5, 1, ((SpinnerNumberModel) (jSpinner_duracaoProcesso2.getModel())).getNumber().intValue(), 1));
        jSpinner_bloqueioProcesso3.setModel(new SpinnerNumberModel(5, 1, ((SpinnerNumberModel) (jSpinner_duracaoProcesso3.getModel())).getNumber().intValue(), 1));
        jSpinner_bloqueioProcesso4.setModel(new SpinnerNumberModel(5, 1, ((SpinnerNumberModel) (jSpinner_duracaoProcesso4.getModel())).getNumber().intValue(), 1));
        jSpinner_bloqueioProcesso5.setModel(new SpinnerNumberModel(5, 1, ((SpinnerNumberModel) (jSpinner_duracaoProcesso5.getModel())).getNumber().intValue(), 1));
        jSpinner_duracaoBloqueioProcesso1.setModel(new SpinnerNumberModel(5, 1, 1000, 1));
        jSpinner_duracaoBloqueioProcesso2.setModel(new SpinnerNumberModel(5, 1, 1000, 1));
        jSpinner_duracaoBloqueioProcesso3.setModel(new SpinnerNumberModel(5, 1, 1000, 1));
        jSpinner_duracaoBloqueioProcesso4.setModel(new SpinnerNumberModel(5, 1, 1000, 1));
        jSpinner_duracaoBloqueioProcesso5.setModel(new SpinnerNumberModel(5, 1, 1000, 1));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_numProcessos = new javax.swing.JLabel();
        jSlider_numProcessos = new javax.swing.JSlider();
        jLabel_quantum = new javax.swing.JLabel();
        jSpinner_quantum = new javax.swing.JSpinner();
        jLabel_overhead = new javax.swing.JLabel();
        jSpinner_overhead = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel_processo1 = new javax.swing.JPanel();
        jLabel_aux1 = new javax.swing.JLabel();
        jLabel_tempoChegada = new javax.swing.JLabel();
        jLabel_tempoExecucao = new javax.swing.JLabel();
        jLabel_instBloqueio = new javax.swing.JLabel();
        jLabel_durBloqueio = new javax.swing.JLabel();
        jLabel_processo1 = new javax.swing.JLabel();
        jSpinner_chegadaProcesso1 = new javax.swing.JSpinner();
        jSpinner_duracaoProcesso1 = new javax.swing.JSpinner();
        jSpinner_bloqueioProcesso1 = new javax.swing.JSpinner();
        jSpinner_duracaoBloqueioProcesso1 = new javax.swing.JSpinner();
        jPanel_processo2 = new javax.swing.JPanel();
        jLabel_processo2 = new javax.swing.JLabel();
        jSpinner_chegadaProcesso2 = new javax.swing.JSpinner();
        jSpinner_duracaoProcesso2 = new javax.swing.JSpinner();
        jSpinner_bloqueioProcesso2 = new javax.swing.JSpinner();
        jSpinner_duracaoBloqueioProcesso2 = new javax.swing.JSpinner();
        jPanel_processo3 = new javax.swing.JPanel();
        jLabel_processo3 = new javax.swing.JLabel();
        jSpinner_chegadaProcesso3 = new javax.swing.JSpinner();
        jSpinner_duracaoProcesso3 = new javax.swing.JSpinner();
        jSpinner_bloqueioProcesso3 = new javax.swing.JSpinner();
        jSpinner_duracaoBloqueioProcesso3 = new javax.swing.JSpinner();
        jPanel_processo4 = new javax.swing.JPanel();
        jLabel_processo4 = new javax.swing.JLabel();
        jSpinner_chegadaProcesso4 = new javax.swing.JSpinner();
        jSpinner_duracaoProcesso4 = new javax.swing.JSpinner();
        jSpinner_bloqueioProcesso4 = new javax.swing.JSpinner();
        jSpinner_duracaoBloqueioProcesso4 = new javax.swing.JSpinner();
        jPanel_processo5 = new javax.swing.JPanel();
        jLabel_processo5 = new javax.swing.JLabel();
        jSpinner_chegadaProcesso5 = new javax.swing.JSpinner();
        jSpinner_duracaoProcesso5 = new javax.swing.JSpinner();
        jSpinner_bloqueioProcesso5 = new javax.swing.JSpinner();
        jSpinner_duracaoBloqueioProcesso5 = new javax.swing.JSpinner();
        jButton_gerarGrafico = new javax.swing.JButton();
        jButton_sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Roud Robin");
        setMinimumSize(new java.awt.Dimension(693, 526));
        setResizable(false);

        jLabel_numProcessos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_numProcessos.setText("Número de Processos:");

        jSlider_numProcessos.setMaximum(5);
        jSlider_numProcessos.setMinimum(1);
        jSlider_numProcessos.setValue(4);
        jSlider_numProcessos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider_numProcessosStateChanged(evt);
            }
        });

        jLabel_quantum.setText("Quantum (ms):");

        jLabel_overhead.setText("Overhead (ms):");

        jPanel_processo1.setName("painel"); // NOI18N
        jPanel_processo1.setOpaque(false);
        jPanel_processo1.setPreferredSize(new java.awt.Dimension(753, 261));

        jLabel_tempoChegada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_tempoChegada.setText("<html><p align=\"center\">Tempo de<br />Chegada (ms)");
        jLabel_tempoChegada.setPreferredSize(new java.awt.Dimension(70, 28));
        jLabel_tempoChegada.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel_tempoExecucao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_tempoExecucao.setText("<html><p align=\"center\">Tempo de<br />Execução (ms)");
        jLabel_tempoExecucao.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel_instBloqueio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_instBloqueio.setText("<html><p align=\"center\">Instante do<br />Bloqueio (ms)");
        jLabel_instBloqueio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel_durBloqueio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_durBloqueio.setText("<html><p align=\"center\">Duração do<br />Bloqueio (ms)");
        jLabel_durBloqueio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel_processo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_processo1.setText("Processo 1:");

        jSpinner_duracaoProcesso1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner_duracaoProcesso1StateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel_processo1Layout = new javax.swing.GroupLayout(jPanel_processo1);
        jPanel_processo1.setLayout(jPanel_processo1Layout);
        jPanel_processo1Layout.setHorizontalGroup(
            jPanel_processo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_processo1Layout.createSequentialGroup()
                .addComponent(jLabel_aux1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jLabel_tempoChegada, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jLabel_tempoExecucao, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jLabel_instBloqueio, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jLabel_durBloqueio, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel_processo1Layout.createSequentialGroup()
                .addComponent(jLabel_processo1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jSpinner_chegadaProcesso1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jSpinner_duracaoProcesso1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(jSpinner_bloqueioProcesso1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jSpinner_duracaoBloqueioProcesso1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel_processo1Layout.setVerticalGroup(
            jPanel_processo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_processo1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_processo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_processo1Layout.createSequentialGroup()
                        .addGroup(jPanel_processo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_aux1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_durBloqueio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_tempoExecucao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_tempoChegada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_processo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_processo1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner_chegadaProcesso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner_duracaoProcesso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner_bloqueioProcesso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner_duracaoBloqueioProcesso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel_instBloqueio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_processo2.setName("painel"); // NOI18N
        jPanel_processo2.setOpaque(false);
        jPanel_processo2.setPreferredSize(new java.awt.Dimension(753, 261));

        jLabel_processo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_processo2.setText("Processo 2:");

        jSpinner_duracaoProcesso2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner_duracaoProcesso2StateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel_processo2Layout = new javax.swing.GroupLayout(jPanel_processo2);
        jPanel_processo2.setLayout(jPanel_processo2Layout);
        jPanel_processo2Layout.setHorizontalGroup(
            jPanel_processo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_processo2Layout.createSequentialGroup()
                .addComponent(jLabel_processo2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jSpinner_chegadaProcesso2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jSpinner_duracaoProcesso2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jSpinner_bloqueioProcesso2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(jSpinner_duracaoBloqueioProcesso2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel_processo2Layout.setVerticalGroup(
            jPanel_processo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_processo2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_processo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner_duracaoBloqueioProcesso2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_processo2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner_chegadaProcesso2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner_duracaoProcesso2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner_bloqueioProcesso2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_processo3.setName("painel"); // NOI18N
        jPanel_processo3.setOpaque(false);
        jPanel_processo3.setPreferredSize(new java.awt.Dimension(753, 261));

        jLabel_processo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_processo3.setText("Processo 3:");

        jSpinner_duracaoProcesso3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner_duracaoProcesso3StateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel_processo3Layout = new javax.swing.GroupLayout(jPanel_processo3);
        jPanel_processo3.setLayout(jPanel_processo3Layout);
        jPanel_processo3Layout.setHorizontalGroup(
            jPanel_processo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_processo3Layout.createSequentialGroup()
                .addComponent(jLabel_processo3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jSpinner_chegadaProcesso3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jSpinner_duracaoProcesso3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jSpinner_bloqueioProcesso3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(jSpinner_duracaoBloqueioProcesso3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel_processo3Layout.setVerticalGroup(
            jPanel_processo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_processo3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_processo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner_duracaoBloqueioProcesso3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_processo3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner_chegadaProcesso3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner_duracaoProcesso3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner_bloqueioProcesso3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_processo4.setName("painel"); // NOI18N
        jPanel_processo4.setOpaque(false);
        jPanel_processo4.setPreferredSize(new java.awt.Dimension(753, 261));

        jLabel_processo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_processo4.setText("Processo 4:");

        jSpinner_duracaoProcesso4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner_duracaoProcesso4StateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel_processo4Layout = new javax.swing.GroupLayout(jPanel_processo4);
        jPanel_processo4.setLayout(jPanel_processo4Layout);
        jPanel_processo4Layout.setHorizontalGroup(
            jPanel_processo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_processo4Layout.createSequentialGroup()
                .addComponent(jLabel_processo4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jSpinner_chegadaProcesso4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jSpinner_duracaoProcesso4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jSpinner_bloqueioProcesso4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(jSpinner_duracaoBloqueioProcesso4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel_processo4Layout.setVerticalGroup(
            jPanel_processo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_processo4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_processo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner_duracaoBloqueioProcesso4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_processo4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner_chegadaProcesso4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner_duracaoProcesso4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner_bloqueioProcesso4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_processo5.setName("painel"); // NOI18N
        jPanel_processo5.setOpaque(false);
        jPanel_processo5.setPreferredSize(new java.awt.Dimension(753, 261));

        jLabel_processo5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_processo5.setText("Processo 5:");

        jSpinner_duracaoProcesso5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner_duracaoProcesso5StateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel_processo5Layout = new javax.swing.GroupLayout(jPanel_processo5);
        jPanel_processo5.setLayout(jPanel_processo5Layout);
        jPanel_processo5Layout.setHorizontalGroup(
            jPanel_processo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_processo5Layout.createSequentialGroup()
                .addComponent(jLabel_processo5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jSpinner_chegadaProcesso5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jSpinner_duracaoProcesso5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jSpinner_bloqueioProcesso5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(jSpinner_duracaoBloqueioProcesso5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel_processo5Layout.setVerticalGroup(
            jPanel_processo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_processo5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_processo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner_duracaoBloqueioProcesso5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_processo5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner_chegadaProcesso5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner_duracaoProcesso5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner_bloqueioProcesso5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton_gerarGrafico.setText("Gerar Gráfico");
        jButton_gerarGrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_gerarGraficoActionPerformed(evt);
            }
        });

        jButton_sair.setText("Sair");
        jButton_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_sairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSlider_numProcessos, 0, 0, Short.MAX_VALUE)
                            .addComponent(jLabel_numProcessos, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSpinner_quantum)
                            .addComponent(jLabel_quantum))
                        .addGap(148, 148, 148)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSpinner_overhead)
                            .addComponent(jLabel_overhead))
                        .addGap(92, 92, 92))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel_processo1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel_processo2, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel_processo3, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel_processo4, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel_processo5, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(80, 80, 80))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(499, Short.MAX_VALUE)
                .addComponent(jButton_gerarGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_numProcessos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_overhead, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_quantum))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinner_quantum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner_overhead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSlider_numProcessos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jPanel_processo1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_processo2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_processo3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_processo4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_processo5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_gerarGrafico)
                    .addComponent(jButton_sair))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSlider_numProcessosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider_numProcessosStateChanged
        // TODO add your handling code here:
        switch (this.jSlider_numProcessos.getValue()) {
            case 1:
                jPanel_processo2.setVisible(false);
                jPanel_processo3.setVisible(false);
                jPanel_processo4.setVisible(false);
                jPanel_processo5.setVisible(false);
                break;
            case 2:
                jPanel_processo2.setVisible(true);
                jPanel_processo3.setVisible(false);
                jPanel_processo4.setVisible(false);
                jPanel_processo5.setVisible(false);
                break;
            case 3:
                jPanel_processo2.setVisible(true);
                jPanel_processo3.setVisible(true);
                jPanel_processo4.setVisible(false);
                jPanel_processo5.setVisible(false);
                break;
            case 4:
                jPanel_processo2.setVisible(true);
                jPanel_processo3.setVisible(true);
                jPanel_processo4.setVisible(true);
                jPanel_processo5.setVisible(false);
                break;
            case 5:
                jPanel_processo2.setVisible(true);
                jPanel_processo3.setVisible(true);
                jPanel_processo4.setVisible(true);
                jPanel_processo5.setVisible(true);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_jSlider_numProcessosStateChanged

    private void jButton_gerarGraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_gerarGraficoActionPerformed
        // TODO add your handling code here:
        int[] tempoChegada = {
            (((SpinnerNumberModel) (jSpinner_chegadaProcesso1.getModel())).getNumber().intValue()),
            (((SpinnerNumberModel) (jSpinner_chegadaProcesso2.getModel())).getNumber().intValue()),
            (((SpinnerNumberModel) (jSpinner_chegadaProcesso3.getModel())).getNumber().intValue()),
            (((SpinnerNumberModel) (jSpinner_chegadaProcesso4.getModel())).getNumber().intValue()),
            (((SpinnerNumberModel) (jSpinner_chegadaProcesso5.getModel())).getNumber().intValue())
        };
        int[] duracao = {
            (((SpinnerNumberModel) (jSpinner_duracaoProcesso1.getModel())).getNumber().intValue()),
            (((SpinnerNumberModel) (jSpinner_duracaoProcesso2.getModel())).getNumber().intValue()),
            (((SpinnerNumberModel) (jSpinner_duracaoProcesso3.getModel())).getNumber().intValue()),
            (((SpinnerNumberModel) (jSpinner_duracaoProcesso4.getModel())).getNumber().intValue()),
            (((SpinnerNumberModel) (jSpinner_duracaoProcesso5.getModel())).getNumber().intValue()),
        };
        int[] tempoBloqueio = {
            (((SpinnerNumberModel) (jSpinner_bloqueioProcesso1.getModel())).getNumber().intValue()),
            (((SpinnerNumberModel) (jSpinner_bloqueioProcesso2.getModel())).getNumber().intValue()),
            (((SpinnerNumberModel) (jSpinner_bloqueioProcesso3.getModel())).getNumber().intValue()),
            (((SpinnerNumberModel) (jSpinner_bloqueioProcesso4.getModel())).getNumber().intValue()),
            (((SpinnerNumberModel) (jSpinner_bloqueioProcesso5.getModel())).getNumber().intValue()),
        };
        int[] duracaoBloqueio = {
            (((SpinnerNumberModel) (jSpinner_duracaoBloqueioProcesso1.getModel())).getNumber().intValue()),
            (((SpinnerNumberModel) (jSpinner_duracaoBloqueioProcesso2.getModel())).getNumber().intValue()),
            (((SpinnerNumberModel) (jSpinner_duracaoBloqueioProcesso3.getModel())).getNumber().intValue()),
            (((SpinnerNumberModel) (jSpinner_duracaoBloqueioProcesso4.getModel())).getNumber().intValue()),
            (((SpinnerNumberModel) (jSpinner_duracaoBloqueioProcesso5.getModel())).getNumber().intValue()),
        };
        Processamento process = new Processamento(
                (((SpinnerNumberModel) (jSpinner_quantum.getModel())).getNumber().intValue()),
                (((SpinnerNumberModel) (jSpinner_overhead.getModel())).getNumber().intValue()),
                jSlider_numProcessos.getValue(), tempoChegada, duracao, tempoBloqueio, duracaoBloqueio);
        process.start();
    }//GEN-LAST:event_jButton_gerarGraficoActionPerformed

    private void jSpinner_duracaoProcesso1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner_duracaoProcesso1StateChanged
        // TODO add your handling code here:
        ((SpinnerNumberModel) (jSpinner_bloqueioProcesso1.getModel())).setMaximum(((SpinnerNumberModel) (jSpinner_duracaoProcesso1.getModel())).getNumber().intValue());
        if (((SpinnerNumberModel) (jSpinner_bloqueioProcesso1.getModel())).getNumber().intValue() > ((SpinnerNumberModel) (jSpinner_duracaoProcesso1.getModel())).getNumber().intValue()) {
            ((SpinnerNumberModel) (jSpinner_bloqueioProcesso1.getModel())).setValue(((SpinnerNumberModel) (jSpinner_duracaoProcesso1.getModel())).getNumber().intValue());
        }
    }//GEN-LAST:event_jSpinner_duracaoProcesso1StateChanged

    private void jSpinner_duracaoProcesso2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner_duracaoProcesso2StateChanged
        // TODO add your handling code here:
        ((SpinnerNumberModel) (jSpinner_bloqueioProcesso2.getModel())).setMaximum(((SpinnerNumberModel) (jSpinner_duracaoProcesso2.getModel())).getNumber().intValue());
        if (((SpinnerNumberModel) (jSpinner_bloqueioProcesso2.getModel())).getNumber().intValue() > ((SpinnerNumberModel) (jSpinner_duracaoProcesso2.getModel())).getNumber().intValue()) {
            ((SpinnerNumberModel) (jSpinner_bloqueioProcesso2.getModel())).setValue(((SpinnerNumberModel) (jSpinner_duracaoProcesso2.getModel())).getNumber().intValue());
        }
    }//GEN-LAST:event_jSpinner_duracaoProcesso2StateChanged

    private void jSpinner_duracaoProcesso3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner_duracaoProcesso3StateChanged
        // TODO add your handling code here:
        ((SpinnerNumberModel) (jSpinner_bloqueioProcesso3.getModel())).setMaximum(((SpinnerNumberModel) (jSpinner_duracaoProcesso3.getModel())).getNumber().intValue());
        if (((SpinnerNumberModel) (jSpinner_bloqueioProcesso3.getModel())).getNumber().intValue() > ((SpinnerNumberModel) (jSpinner_duracaoProcesso3.getModel())).getNumber().intValue()) {
            ((SpinnerNumberModel) (jSpinner_bloqueioProcesso3.getModel())).setValue(((SpinnerNumberModel) (jSpinner_duracaoProcesso3.getModel())).getNumber().intValue());
        }
    }//GEN-LAST:event_jSpinner_duracaoProcesso3StateChanged

    private void jSpinner_duracaoProcesso4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner_duracaoProcesso4StateChanged
        // TODO add your handling code here:
        ((SpinnerNumberModel) (jSpinner_bloqueioProcesso4.getModel())).setMaximum(((SpinnerNumberModel) (jSpinner_duracaoProcesso4.getModel())).getNumber().intValue());
        if (((SpinnerNumberModel) (jSpinner_bloqueioProcesso4.getModel())).getNumber().intValue() > ((SpinnerNumberModel) (jSpinner_duracaoProcesso4.getModel())).getNumber().intValue()) {
            ((SpinnerNumberModel) (jSpinner_bloqueioProcesso4.getModel())).setValue(((SpinnerNumberModel) (jSpinner_duracaoProcesso4.getModel())).getNumber().intValue());
        }
    }//GEN-LAST:event_jSpinner_duracaoProcesso4StateChanged

    private void jSpinner_duracaoProcesso5StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner_duracaoProcesso5StateChanged
        // TODO add your handling code here:
        ((SpinnerNumberModel) (jSpinner_bloqueioProcesso5.getModel())).setMaximum(((SpinnerNumberModel) (jSpinner_duracaoProcesso5.getModel())).getNumber().intValue());
        if (((SpinnerNumberModel) (jSpinner_bloqueioProcesso5.getModel())).getNumber().intValue() > ((SpinnerNumberModel) (jSpinner_duracaoProcesso5.getModel())).getNumber().intValue()) {
            ((SpinnerNumberModel) (jSpinner_bloqueioProcesso5.getModel())).setValue(((SpinnerNumberModel) (jSpinner_duracaoProcesso5.getModel())).getNumber().intValue());
        }
    }//GEN-LAST:event_jSpinner_duracaoProcesso5StateChanged

    private void jButton_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_sairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton_sairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new InterfaceGrafica().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_gerarGrafico;
    private javax.swing.JButton jButton_sair;
    private javax.swing.JLabel jLabel_aux1;
    private javax.swing.JLabel jLabel_durBloqueio;
    private javax.swing.JLabel jLabel_instBloqueio;
    private javax.swing.JLabel jLabel_numProcessos;
    private javax.swing.JLabel jLabel_overhead;
    private javax.swing.JLabel jLabel_processo1;
    private javax.swing.JLabel jLabel_processo2;
    private javax.swing.JLabel jLabel_processo3;
    private javax.swing.JLabel jLabel_processo4;
    private javax.swing.JLabel jLabel_processo5;
    private javax.swing.JLabel jLabel_quantum;
    private javax.swing.JLabel jLabel_tempoChegada;
    private javax.swing.JLabel jLabel_tempoExecucao;
    private javax.swing.JPanel jPanel_processo1;
    private javax.swing.JPanel jPanel_processo2;
    private javax.swing.JPanel jPanel_processo3;
    private javax.swing.JPanel jPanel_processo4;
    private javax.swing.JPanel jPanel_processo5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSlider jSlider_numProcessos;
    private javax.swing.JSpinner jSpinner_bloqueioProcesso1;
    private javax.swing.JSpinner jSpinner_bloqueioProcesso2;
    private javax.swing.JSpinner jSpinner_bloqueioProcesso3;
    private javax.swing.JSpinner jSpinner_bloqueioProcesso4;
    private javax.swing.JSpinner jSpinner_bloqueioProcesso5;
    private javax.swing.JSpinner jSpinner_chegadaProcesso1;
    private javax.swing.JSpinner jSpinner_chegadaProcesso2;
    private javax.swing.JSpinner jSpinner_chegadaProcesso3;
    private javax.swing.JSpinner jSpinner_chegadaProcesso4;
    private javax.swing.JSpinner jSpinner_chegadaProcesso5;
    private javax.swing.JSpinner jSpinner_duracaoBloqueioProcesso1;
    private javax.swing.JSpinner jSpinner_duracaoBloqueioProcesso2;
    private javax.swing.JSpinner jSpinner_duracaoBloqueioProcesso3;
    private javax.swing.JSpinner jSpinner_duracaoBloqueioProcesso4;
    private javax.swing.JSpinner jSpinner_duracaoBloqueioProcesso5;
    private javax.swing.JSpinner jSpinner_duracaoProcesso1;
    private javax.swing.JSpinner jSpinner_duracaoProcesso2;
    private javax.swing.JSpinner jSpinner_duracaoProcesso3;
    private javax.swing.JSpinner jSpinner_duracaoProcesso4;
    private javax.swing.JSpinner jSpinner_duracaoProcesso5;
    private javax.swing.JSpinner jSpinner_overhead;
    private javax.swing.JSpinner jSpinner_quantum;
    // End of variables declaration//GEN-END:variables
}
