package roundrobin;

import java.awt.Component;
import javax.swing.UIManager;

/**
 *
 * @author Diogo
 */
public class TabelaFinal extends javax.swing.JFrame {

    /** Creates new form InterfaceGrafica */
    public TabelaFinal(Component cmpt, int numProcessos, int[] tempoTotalExec, int[] tempoResp, int[] tempoEsp) {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
        } catch (Exception e) {
            e.printStackTrace();
        }
        initComponents();
        setLocationRelativeTo(cmpt);
        setLocation(this.getLocation().x, this.getLocation().y + cmpt.getHeight());
        if (numProcessos < 5) {
            jPanel_processo5.setVisible(false);
        } else {
            jTextField_execucao_processo5.setText(String.valueOf(tempoTotalExec[4]));
            jTextField_resposta_processo5.setText(String.valueOf(tempoResp[4]));
            jTextField_espera_processo5.setText(String.valueOf(tempoEsp[4]));
        }
        if (numProcessos < 4) {
            jPanel_processo4.setVisible(false);
        } else {
            jTextField_execucao_processo4.setText(String.valueOf(tempoTotalExec[3]));
            jTextField_resposta_processo4.setText(String.valueOf(tempoResp[3]));
            jTextField_espera_processo4.setText(String.valueOf(tempoEsp[3]));
        }
        if (numProcessos < 3) {
            jPanel_processo3.setVisible(false);
        } else {
            jTextField_execucao_processo3.setText(String.valueOf(tempoTotalExec[2]));
            jTextField_resposta_processo3.setText(String.valueOf(tempoResp[2]));
            jTextField_espera_processo3.setText(String.valueOf(tempoEsp[2]));
        }
        if (numProcessos < 2) {
            jPanel_processo2.setVisible(false);
        } else {
            jTextField_execucao_processo2.setText(String.valueOf(tempoTotalExec[1]));
            jTextField_resposta_processo2.setText(String.valueOf(tempoResp[1]));
            jTextField_espera_processo2.setText(String.valueOf(tempoEsp[1]));
        }
        jTextField_execucao_processo1.setText(String.valueOf(tempoTotalExec[0]));
        jTextField_resposta_processo1.setText(String.valueOf(tempoResp[0]));
        jTextField_espera_processo1.setText(String.valueOf(tempoEsp[0]));
        float tempoTotalExecucao = 0;
        float tempoTotalEspera = 0;
        float tempoTotalResposta = 0;
        for (int i = 0; i < 5; i++) {
            tempoTotalExecucao = tempoTotalExecucao + tempoTotalExec[i];
            tempoTotalEspera = tempoTotalEspera + tempoEsp[i];
            tempoTotalResposta = tempoTotalResposta + tempoResp[i];
        }
        jTextField_execucao_media.setText(String.valueOf(tempoTotalExecucao / numProcessos));
        jTextField_resposta_media.setText(String.valueOf(tempoTotalResposta / numProcessos));
        jTextField_espera_media.setText(String.valueOf(tempoTotalEspera / numProcessos));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_processo1 = new javax.swing.JPanel();
        jLabel_aux1 = new javax.swing.JLabel();
        jLabel_tempoChegada = new javax.swing.JLabel();
        jLabel_tempoExecucao = new javax.swing.JLabel();
        jLabel_instBloqueio = new javax.swing.JLabel();
        jLabel_processo1 = new javax.swing.JLabel();
        jTextField_execucao_processo1 = new javax.swing.JTextField();
        jTextField_resposta_processo1 = new javax.swing.JTextField();
        jTextField_espera_processo1 = new javax.swing.JTextField();
        jPanel_processo2 = new javax.swing.JPanel();
        jLabel_processo2 = new javax.swing.JLabel();
        jTextField_execucao_processo2 = new javax.swing.JTextField();
        jTextField_resposta_processo2 = new javax.swing.JTextField();
        jTextField_espera_processo2 = new javax.swing.JTextField();
        jPanel_processo3 = new javax.swing.JPanel();
        jLabel_processo3 = new javax.swing.JLabel();
        jTextField_execucao_processo3 = new javax.swing.JTextField();
        jTextField_resposta_processo3 = new javax.swing.JTextField();
        jTextField_espera_processo3 = new javax.swing.JTextField();
        jPanel_processo4 = new javax.swing.JPanel();
        jLabel_processo4 = new javax.swing.JLabel();
        jTextField_execucao_processo4 = new javax.swing.JTextField();
        jTextField_resposta_processo4 = new javax.swing.JTextField();
        jTextField_espera_processo4 = new javax.swing.JTextField();
        jPanel_processo5 = new javax.swing.JPanel();
        jLabel_processo5 = new javax.swing.JLabel();
        jTextField_execucao_processo5 = new javax.swing.JTextField();
        jTextField_resposta_processo5 = new javax.swing.JTextField();
        jTextField_espera_processo5 = new javax.swing.JTextField();
        jPanel_media = new javax.swing.JPanel();
        jLabel_media = new javax.swing.JLabel();
        jTextField_execucao_media = new javax.swing.JTextField();
        jTextField_resposta_media = new javax.swing.JTextField();
        jTextField_espera_media = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Roud Robin");
        setResizable(false);

        jPanel_processo1.setName("painel"); // NOI18N
        jPanel_processo1.setOpaque(false);
        jPanel_processo1.setPreferredSize(new java.awt.Dimension(753, 261));

        jLabel_tempoChegada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_tempoChegada.setText("<html><p align=\"center\">Tempo total de<br />Execução (ms)");
        jLabel_tempoChegada.setPreferredSize(new java.awt.Dimension(70, 28));
        jLabel_tempoChegada.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel_tempoExecucao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_tempoExecucao.setText("<html><p align=\"center\">Tempo de<br />Resposta (ms)");
        jLabel_tempoExecucao.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel_instBloqueio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_instBloqueio.setText("<html><p align=\"center\">Tempo de<br />Espera (ms)");
        jLabel_instBloqueio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel_processo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_processo1.setText("Processo 1:");

        jTextField_execucao_processo1.setEditable(false);
        jTextField_execucao_processo1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField_resposta_processo1.setEditable(false);
        jTextField_resposta_processo1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField_espera_processo1.setEditable(false);
        jTextField_espera_processo1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel_processo1Layout = new javax.swing.GroupLayout(jPanel_processo1);
        jPanel_processo1.setLayout(jPanel_processo1Layout);
        jPanel_processo1Layout.setHorizontalGroup(
            jPanel_processo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_processo1Layout.createSequentialGroup()
                .addComponent(jLabel_aux1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jLabel_tempoChegada, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jLabel_tempoExecucao, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jLabel_instBloqueio, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(jPanel_processo1Layout.createSequentialGroup()
                .addComponent(jLabel_processo1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(jTextField_execucao_processo1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(jTextField_resposta_processo1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(jTextField_espera_processo1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel_processo1Layout.setVerticalGroup(
            jPanel_processo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_processo1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_processo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_aux1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_tempoExecucao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_tempoChegada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_instBloqueio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_processo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_processo1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_execucao_processo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_resposta_processo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_espera_processo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel_processo2.setName("painel"); // NOI18N
        jPanel_processo2.setOpaque(false);
        jPanel_processo2.setPreferredSize(new java.awt.Dimension(753, 261));

        jLabel_processo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_processo2.setText("Processo 2:");

        jTextField_execucao_processo2.setEditable(false);
        jTextField_execucao_processo2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField_resposta_processo2.setEditable(false);
        jTextField_resposta_processo2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField_espera_processo2.setEditable(false);
        jTextField_espera_processo2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel_processo2Layout = new javax.swing.GroupLayout(jPanel_processo2);
        jPanel_processo2.setLayout(jPanel_processo2Layout);
        jPanel_processo2Layout.setHorizontalGroup(
            jPanel_processo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_processo2Layout.createSequentialGroup()
                .addComponent(jLabel_processo2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(jTextField_execucao_processo2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(jTextField_resposta_processo2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(jTextField_espera_processo2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel_processo2Layout.setVerticalGroup(
            jPanel_processo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_processo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel_processo2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTextField_execucao_processo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTextField_resposta_processo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTextField_espera_processo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel_processo3.setName("painel"); // NOI18N
        jPanel_processo3.setOpaque(false);
        jPanel_processo3.setPreferredSize(new java.awt.Dimension(753, 261));

        jLabel_processo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_processo3.setText("Processo 3:");

        jTextField_execucao_processo3.setEditable(false);
        jTextField_execucao_processo3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField_resposta_processo3.setEditable(false);
        jTextField_resposta_processo3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField_espera_processo3.setEditable(false);
        jTextField_espera_processo3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel_processo3Layout = new javax.swing.GroupLayout(jPanel_processo3);
        jPanel_processo3.setLayout(jPanel_processo3Layout);
        jPanel_processo3Layout.setHorizontalGroup(
            jPanel_processo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_processo3Layout.createSequentialGroup()
                .addComponent(jLabel_processo3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(jTextField_execucao_processo3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(jTextField_resposta_processo3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(jTextField_espera_processo3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel_processo3Layout.setVerticalGroup(
            jPanel_processo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_processo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel_processo3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTextField_execucao_processo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTextField_resposta_processo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTextField_espera_processo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel_processo4.setName("painel"); // NOI18N
        jPanel_processo4.setOpaque(false);
        jPanel_processo4.setPreferredSize(new java.awt.Dimension(753, 261));

        jLabel_processo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_processo4.setText("Processo 4:");

        jTextField_execucao_processo4.setEditable(false);
        jTextField_execucao_processo4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField_resposta_processo4.setEditable(false);
        jTextField_resposta_processo4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField_espera_processo4.setEditable(false);
        jTextField_espera_processo4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel_processo4Layout = new javax.swing.GroupLayout(jPanel_processo4);
        jPanel_processo4.setLayout(jPanel_processo4Layout);
        jPanel_processo4Layout.setHorizontalGroup(
            jPanel_processo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_processo4Layout.createSequentialGroup()
                .addComponent(jLabel_processo4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(jTextField_execucao_processo4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(jTextField_resposta_processo4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(jTextField_espera_processo4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel_processo4Layout.setVerticalGroup(
            jPanel_processo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_processo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel_processo4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTextField_execucao_processo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTextField_resposta_processo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTextField_espera_processo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel_processo5.setName("painel"); // NOI18N
        jPanel_processo5.setOpaque(false);
        jPanel_processo5.setPreferredSize(new java.awt.Dimension(753, 261));

        jLabel_processo5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_processo5.setText("Processo 5:");

        jTextField_execucao_processo5.setEditable(false);
        jTextField_execucao_processo5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField_resposta_processo5.setEditable(false);
        jTextField_resposta_processo5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField_espera_processo5.setEditable(false);
        jTextField_espera_processo5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel_processo5Layout = new javax.swing.GroupLayout(jPanel_processo5);
        jPanel_processo5.setLayout(jPanel_processo5Layout);
        jPanel_processo5Layout.setHorizontalGroup(
            jPanel_processo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_processo5Layout.createSequentialGroup()
                .addComponent(jLabel_processo5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(jTextField_execucao_processo5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(jTextField_resposta_processo5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(jTextField_espera_processo5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel_processo5Layout.setVerticalGroup(
            jPanel_processo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_processo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel_processo5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTextField_execucao_processo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTextField_resposta_processo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTextField_espera_processo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel_media.setName("painel"); // NOI18N
        jPanel_media.setOpaque(false);
        jPanel_media.setPreferredSize(new java.awt.Dimension(753, 261));

        jLabel_media.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_media.setText("Média:");

        jTextField_execucao_media.setEditable(false);
        jTextField_execucao_media.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField_resposta_media.setEditable(false);
        jTextField_resposta_media.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField_espera_media.setEditable(false);
        jTextField_espera_media.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel_mediaLayout = new javax.swing.GroupLayout(jPanel_media);
        jPanel_media.setLayout(jPanel_mediaLayout);
        jPanel_mediaLayout.setHorizontalGroup(
            jPanel_mediaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_mediaLayout.createSequentialGroup()
                .addComponent(jLabel_media, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(jTextField_execucao_media, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(jTextField_resposta_media, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(jTextField_espera_media, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel_mediaLayout.setVerticalGroup(
            jPanel_mediaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_mediaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel_media, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTextField_execucao_media, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTextField_resposta_media, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTextField_espera_media, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel_media, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                    .addComponent(jPanel_processo2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                    .addComponent(jPanel_processo1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                    .addComponent(jPanel_processo3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                    .addComponent(jPanel_processo4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                    .addComponent(jPanel_processo5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_processo1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_processo2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_processo3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_processo4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_processo5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jPanel_media, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new InterfaceGrafica().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_aux1;
    private javax.swing.JLabel jLabel_instBloqueio;
    private javax.swing.JLabel jLabel_media;
    private javax.swing.JLabel jLabel_processo1;
    private javax.swing.JLabel jLabel_processo2;
    private javax.swing.JLabel jLabel_processo3;
    private javax.swing.JLabel jLabel_processo4;
    private javax.swing.JLabel jLabel_processo5;
    private javax.swing.JLabel jLabel_tempoChegada;
    private javax.swing.JLabel jLabel_tempoExecucao;
    private javax.swing.JPanel jPanel_media;
    private javax.swing.JPanel jPanel_processo1;
    private javax.swing.JPanel jPanel_processo2;
    private javax.swing.JPanel jPanel_processo3;
    private javax.swing.JPanel jPanel_processo4;
    private javax.swing.JPanel jPanel_processo5;
    private javax.swing.JTextField jTextField_espera_media;
    private javax.swing.JTextField jTextField_espera_processo1;
    private javax.swing.JTextField jTextField_espera_processo2;
    private javax.swing.JTextField jTextField_espera_processo3;
    private javax.swing.JTextField jTextField_espera_processo4;
    private javax.swing.JTextField jTextField_espera_processo5;
    private javax.swing.JTextField jTextField_execucao_media;
    private javax.swing.JTextField jTextField_execucao_processo1;
    private javax.swing.JTextField jTextField_execucao_processo2;
    private javax.swing.JTextField jTextField_execucao_processo3;
    private javax.swing.JTextField jTextField_execucao_processo4;
    private javax.swing.JTextField jTextField_execucao_processo5;
    private javax.swing.JTextField jTextField_resposta_media;
    private javax.swing.JTextField jTextField_resposta_processo1;
    private javax.swing.JTextField jTextField_resposta_processo2;
    private javax.swing.JTextField jTextField_resposta_processo3;
    private javax.swing.JTextField jTextField_resposta_processo4;
    private javax.swing.JTextField jTextField_resposta_processo5;
    // End of variables declaration//GEN-END:variables
}
